markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: krymee
author: "phiix"
email: achxku#163.com
name: "Xin.I.D.E.A"
url: http://www.xinidea.cn
domain: www.xinidea.cn
all_categories: [
["service", "Linux服务","/posts/service.html"], 
["program", "软件编程","/posts/program.html"],
["web", "Web建站","/posts/web.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
